const { default: FG3000 } = require("../components/glues/fg3000");
const { default: FG6500 } = require("../components/glues/fg6500");
const { default: HM2505 } = require("../components/glues/hm2505");
const { default: HM980 } = require("../components/glues/hm980");

const adhesives = [
  {
    name: 65-301,
    glue: "cold glue",
    type: "Partial Copolymer Resin",
    image: "",
    description: "ADSPEC 65-301 is a partial copolymer resin that has excellent adhesion to difficult substrates",
    industries: "Folding Cartons, Can Labels, Assembly",
    color: "White",
    packaging: "30, 55 gallon Drums, Totes or Pails",
    remarks: "ADSPEC 65-301 conforms to federal specifications 121.2520 for food packaging",
    "shelf life": "3 months"
  },
  {
    name: 3003,
    glue: "cold glue",
    type: "dextrin",
    image: "", 
    description: "High Tack Dextrin based adhesive with excellent stability, designed for bonding paper and corrugated substrates", 
    industries: "Bag and Box",
    color: "amber",
    packaging: "30, 55 gallon Drums, Totes or Pails",
    remarks: "ADSPEC# 3003 conforms to federal specifications 121.2520 for food packaging",
    "shelf life": "3 months"
  },
  {
    name: 4302,
    glue: "cold glue",
    type: "resin paste",
    image: "",
    description: "ADSPEC 65-301 is a partial copolymer resin that has excellent adhesion to difficult substrates",
    industries: "bag",
    color: "opaque",
    packaging: "30, 55 gallon Drums, Totes or Pails",
    remarks: "ADSPEC# 4302 conforms to federal specification composition requirements of indirect food additive regulations 21 CFR 175.105 ADHESIVES",
    "shelf life": "3 months"
  },
  {
    name: 5525,
    glue: "cold glue",
    type: "Homopolymer",
    image: "",
    description: "ADSPEC# 5525 is formulated synthetic resin emulsion that develops high initial wet tack with good latitude. It machine well",
    industries: "Corrugated",
    color:"Wet-White / Dry Clear",
    packaging: "30, 55 gallon Drums, Totes or Pails",
    remarks: "ADSPEC# 5525 conforms to federal specification composition requirements of indirect food additive regulations 21 CFR 175.105 ADHESIVES",
    "shelf life": "3 months"
  },
  {
    name: 5690,
    glue: "cold glue",
    type: "Homopolymer",
    image: "",
    description: "ADSPEC# 5690 is a fast tacking adhesives developed for tube winding and solid fiber laminating. It is ready for use, but may be diluted with water if desired",
    industries: "Corrugated",
    color: "opaque",
    packaging: "30, 55 gallon Drums, Totes or Pails",
    remarks: "ADSPEC# 5690 conforms to federal specifications 121.2520 for food packaging",
    "shelf life": "3 months"
  },
  {
    name: 5890,
    glue: "cold glue",
    type: "Homopolymer",
    image: "",
    description: "ADSPEC# 5690 is a fast tacking adhesives developed for tube winding and solid fiber laminating. It is ready for use, but may be diluted with water if desired",
    industries: "Corrugated",
    color: "opaque",
    packaging: "30, 55 gallon Drums, Totes or Pails",
    remarks: "ADSPEC# 5690 conforms to federal specifications 121.2520 for food packaging",
    "shelf life": "3 months"
  },
  {
    name: 85-301,
    glue: "cold glue",
    type: "Copolymer",
    image: "",
    description: "ADSPEC# 85-301 is a formulated synthetic resin emulsion that develops excellent initial wet tack with good latitude. It machines well and is used for hard to stick surfaces",
    industries: "Packaging",
    color: "Wet-White / Dry Clear",
    packaging: "30, 55 gallon Drums, Totes or Pails",
    remarks: "ADSPEC# 85-301 confirms to federal specification composition requirements of indirect food additive regulations 21 CFR 175.105 ADHESIVES",
    "shelf life": "3 months"
  },
  {
    name: FG3000,
    glue: "pressure sensitive",
    type: "pressure sensitive",
    image: "",
    description: "FG3000 is a Pressure Sensitive Hot Melt designed for laminating, Coating, and Hand Work Applications",
    industries: "",
    color: "",
    packaging: "",
    remarks: "",
    "shelf life": ""
  },
  {
    name: FG6500,
    glue: "pressure sensitive",
    type: "pressure sensitive",
    image: "",
    description: "FG6500 is a Pressure Sensitive Hot Melt designed for laminating, Coating, and Hand Work Applications",
    industries: "",
    color: "",
    packaging: "",
    remarks: "",
    "shelf life": ""
  },
  {
    name: HM980,
    glue: "hot melt",
    type: "High Temp – Heavily Coating Wax Box Case Seal",
    image: "",
    description: "",
    industries: "Meat and Poultry",
    color: "",
    packaging: "pellets",
    remarks: "",
    "shelf life": "",
    advantages: ["Chemically penetrates through coating vs. raising temperatures", "100% Fiber tear on most difficult applications", "Will bond double sided -heavy waxed surfaces", "Excellent thermal stability", "High tack / Fast set", "Freezer grade", "Bonds to a wide range of difficult substrates" ]
  },
  {
    name: HM2505,
    glue: "hot melt",
    type: "hot melt",
    image: "",
    description: "",
    industries: "Frozen Foods, Holographic folding cartons",
    color: "",
    packaging: "pellets",
    remarks: "",
    "shelf life": "",
    advantages: ["Freezer Grade: Performs extremely well in cold environments", "Safety: The severity of a burn depends on the length of time that the area is held above the burn temperature. For example, 1 gramme of a traditional 350°, F hot melt requires 18 seconds to cool down below 180F, and will be constantly burning during those 18 seconds. Applied at 250°F, only 70°F above the burn temperature, Low Temperature hot Melts will significantly reduce the occurrence of severe burns", "Reduced energy use: Measurements carried out in a production process showed that Low Temperature hot melts requires 33% less energy from the hot melt unit, all along the production cycle. This can produce considerable savings in a multi-line plant. The reduction in energy use will have a positive impact on the environment, and this is an important KPI for many leading food producers and Supermarkets", "Improved Stability: Decrease in the thermal degradation of the adhesive", "Reduced Downtime: Reduce char generated in an adhesive application", "Reduced Maintenance Cost: 100°F difference reduces wear and tear on machinery", "Efficiency: Fast set speeds of Low temp have improve line speeds by 30%"]
  },
  {
    name: HM3060,
    glue: "hot melt",
    type: "hot melt",
    image: "",
    description: "",
    industries: "Frozen Foods, Holographic folding cartons",
    color: "",
    packaging: "pellets",
    remarks: "",
    "shelf life": "",
    advantages: ["Safety: The severity of a burn depends on the length of time that the area is held above the burn temperature. For example, 1 gramme of a traditional 350°F hot melt requires 18 seconds to cool down below 180°F, and will be constantly burning during those 18 seconds. Applied at 250°F, only 70°F above the burn temperature, Low Temperature hot Melts will significantly reduce the occurrence of severe burns", "Reduced energy use: Measurements carried out in a production process showed that Low Temperature hot melts requires 33% less energy from the hot melt unit, all along the production cycle. This can produce considerable savings in a multi-line plant. The reduction in energy use will have a positive impact on the environment, and this is an important KPI for many leading food producers and Supermarkets", "Improved Stability: Decrease in the thermal degradation of the adhesive", "Reduced Downtime: Reduce char generated in an adhesive application", "Reduced Maintenance Cost: 100°F difference reduces wear and tear on machinery", "Efficiency: Fast set speeds of Low temp have improve line speeds by 30%"]
  },
  {
    name: HM4500,
    glue: "hot melt",
    type: "hot melt",
    image: "",
    description: "",
    industries: "",
    color: "",
    packaging: "pellets",
    remarks: "",
    "shelf life": "",
    advantages: ["Safety: The severity of a burn depends on the length of time that the area is held above the burn temperature. For example, 1 gramme of a traditional 350°, F hot melt requires 18 seconds to cool down below 180F, and will be constantly burning during those 18 seconds. Applied at 250°F, only 70°F above the burn temperature, Low Temperature hot Melts will significantly reduce the occurrence of severe burns", "Reduced energy use: Measurements carried out in a production process showed that Low Temperature hot melts requires 33% less energy from the hot melt unit, all along the production cycle. This can produce considerable savings in a multi-line plant. The reduction in energy use will have a positive impact on the environment, and this is an important KPI for many leading food producers and Supermarkets", "Improved Stability: Decrease in the thermal degradation of the adhesive"]
  },
  {
    name: HM8020,
    glue: "hot melt",
    type: "hot melt",
    image: "",
    description: "",
    industries: "Folding carton, Case / Carton Seal, Tray forming",
    color: "",
    packaging: "pellets",
    remarks: "",
    "shelf life": "",
    advantages: ["Heat resistant up to 180°F", "Excellent thermal stability", "Good Peal Strength", "Short Set times", "Fast Tact", "Freezer Grade"]
  },
  {
    name: HSLA9085,
    glue: "presure sensitive",
    type: "presure sensitive",
    image: "",
    description: "HSLA9085 is a Pressure Sensitive Hot Melt designed for laminating, Coating, and Hand Work Applications",
    industries: "",
    color: "",
    packaging: "pellets",
    remarks: "",
    "shelf life": "",
    advantages: []
  },
  {
    name: PS160,
    glue: "presure sensitive",
    type: "presure sensitive",
    image: "",
    description: "Pressure Sensitive Hot Melt designed for laminating, Coating, and Hand Work Applications",
    industries: "",
    color: "",
    packaging: "pellets",
    remarks: "Pressure Sensitive Hot Melt designed for laminating, Coating, and Hand Work Applications",
    "shelf life": "",
    advantages: []
  },
  {
    name: PS505,
    glue: "presure sensitive",
    type: "presure sensitive",
    image: "",
    description: "Pressure Sensitive Hot Melt designed for laminating, Coating, and Hand Work Applications",
    industries: "",
    color: "",
    packaging: "pellets",
    remarks: "Pressure Sensitive Hot Melt designed for laminating, Coating, and Hand Work Applications",
    "shelf life": "",
    advantages: []
  },
  {
    name: PS3000,
    glue: "presure sensitive",
    type: "presure sensitive",
    image: "",
    description: "Pressure Sensitive Hot Melt designed for laminating, Coating, and Hand Work Applications",
    industries: "",
    color: "",
    packaging: "pellets",
    remarks: "Pressure Sensitive Hot Melt designed for laminating, Coating, and Hand Work Applications",
    "shelf life": "",
    advantages: []
  },
  {
    name: SM1523,
    glue: "hot melt",
    type: "Metallocene Hybrid",
    image: "",
    description: "",
    industries: "Folding carton, Case Seal, Corrugated, Tray foriming",
    color: "",
    packaging: "pellets",
    remarks: "",
    advantages: ["Cost Savings – 30% less than traditional Metallocene", "Efficiency: Fast set speeds improve line speeds", "Freezer Grade: Performs extremely well in cold environments", "Improved Stability: Decrease in the thermal degradation", "Reduced Downtime: Reduces char generated in an adhesive application"]
  },
  {
    name: SM1831,
    glue: "hot melt",
    type: "Metallocene Hybrid",
    image: "",
    description: "",
    industries: "Folding carton, Case Seal, Corrugated, Tray foriming",
    color: "",
    packaging: "pellets",
    remarks: "",
    advantages: ["Efficiency: Fast set speeds improve line speeds", "Freezer Grade: Performs extremely well in cold environments", "Improved Stability: Decrease in the thermal degradation", "Reduced Downtime: Reduces char generated in an adhesive application"]
  },
  {
    name: SM3150,
    glue: "hot melt",
    type: "",
    image: "",
    description: "",
    industries: "Folding carton, Case Seal, Corrugated, Tray foriming",
    color: "",
    packaging: "pellets",
    remarks: "",
    "shelf life": "",
    advantages: ["Improved Stability: Decrease in the thermal degradation of the adhesive", "Reduced Downtime: Reduce char generated in an adhesive application", "Reduced Maintenance Cost: Metallocene Hot Melt never chars", "Efficiency: Fast set speeds of Low temp have improve line speeds by 30%", "Bonds to a wide range of difficult substrates", "Light color will enhance your package appearance", "Odor free, smoke free, user-friendly work environment", "Retain its clarity after many hours of use"]
  },
  {
    name: SM7834,
    glue: "hot melt",
    type: "",
    image: "",
    description: "",
    industries: "Folding carton, Case Seal, Corrugated, Tray foriming",
    color: "",
    packaging: "pellets",
    remarks: "",
    "shelf life": "",
    advantages: ["Improved Stability: Decrease in the thermal degradation of the adhesive", "Reduced Downtime: Reduce char generated in an adhesive application", "Reduced Maintenance Cost: Metallocene Hot Melt never chars", "Efficiency: Fast set speeds of Low temp have improve line speeds by 30%", "Bonds to a wide range of difficult substrates", "Light color will enhance your package appearance", "Odor free, smoke free, user-friendly work environment", "Retain its clarity after many hours of use"]
  },
]